// src/ui/react/fancy-toolbar/modules/main/Toolbar.tsx
import { DragDropProvider, DragOverlay } from "@dnd-kit/react";
import { move } from "@dnd-kit/helpers";
import { invoke, SeelenCommand } from "@seelen-ui/lib";
import { cx } from "libs/ui/react/utils/styling.ts";
import { useCallback } from "preact/compat";

import { BackgroundByLayersV2 } from "libs/ui/react/components/BackgroundByLayers/infra.tsx";

import {
  $plugins,
  $toolbar_state,
  HARDCODED_SEPARATOR_LEFT,
  HARDCODED_SEPARATOR_RIGHT,
} from "../shared/state/items.ts";
import { $settings } from "../shared/state/settings.ts";
import { Alignment, FancyToolbarSide } from "@seelen-ui/lib/types";
import { Group } from "./ItemsContainer.tsx";
import { Item } from "../item/infra/infra.tsx";
import { $thereIsMaximizedOnBg } from "../shared/state/windows.ts";
import { $hidden_by_autohide } from "../shared/state/hidden.ts";
import { ShowDesktopButton } from "./CornerAction.tsx";
import { useMainContextMenu } from "./ContextMenu.tsx";
import { matchIds } from "../shared/utils.ts";
import { useComputed } from "@preact/signals";
import { DND_PLUGINS, DND_SENSORS } from "libs/ui/dnd.ts";

export function FancyToolbar() {
  const splittedItems = useComputed(() => {
    const items = $toolbar_state.value.items;
    const idx1 = items.findIndex(
      (i) => typeof i !== "string" && i.id === HARDCODED_SEPARATOR_LEFT.id,
    );
    const idx2 = items.findIndex(
      (i) => typeof i !== "string" && i.id === HARDCODED_SEPARATOR_RIGHT.id,
    );

    // center includes the separator items
    return {
      left: items.slice(0, idx1),
      center: items.slice(idx1, idx2 + 1),
      right: items.slice(idx2 + 1),
    };
  });

  const contextMenuDef = useMainContextMenu();

  const onContextMenu = useCallback(() => {
    const alignY = $settings.value.position === FancyToolbarSide.Bottom ? Alignment.End : Alignment.Start;
    invoke(SeelenCommand.TriggerContextMenu, {
      menu: { ...contextMenuDef, alignX: Alignment.Center, alignY },
      forwardTo: null,
    });
  }, [contextMenuDef, $settings.value.position]);

  return (
    <div
      className={cx("ft-bar", $settings.value.position.toLowerCase(), {
        "ft-bar-hidden": $hidden_by_autohide.value,
      })}
      data-has-margin={!!$settings.value.margin}
      data-there-is-maximized-on-background={$thereIsMaximizedOnBg.value}
      onContextMenu={onContextMenu}
    >
      <ShowDesktopButton />
      <BackgroundByLayersV2 />

      <DragDropProvider
        plugins={DND_PLUGINS}
        sensors={DND_SENSORS}
        onDragOver={(event) => {
          const temp = $toolbar_state.value.items.map((item) => typeof item === "string" ? item : item.id);
          const newItems = move(temp, event);

          $toolbar_state.value = {
            isReorderDisabled: $toolbar_state.value.isReorderDisabled,
            items: newItems.map((id) => $toolbar_state.value.items.find((i) => matchIds(i, id))!),
          };
        }}
      >
        <Group id="left" items={splittedItems.value.left} startIndex={0} />
        <Group
          id="center"
          items={splittedItems.value.center}
          startIndex={splittedItems.value.left.length}
        />
        <Group
          id="right"
          items={splittedItems.value.right}
          startIndex={splittedItems.value.left.length + splittedItems.value.center.length}
        />

        <DragOverlay>
          {(source) => {
            const allItems = $toolbar_state.value.items;
            const entry = allItems.find((i) => matchIds(i, source.id as string));
            if (!entry) return null;

            if (typeof entry === "string") {
              const plugin = $plugins.value.find((p) => p.id === entry);
              if (!plugin) return null;
              const module = { ...(plugin.plugin as any), id: entry };
              return <Item module={module} index={0} />;
            }

            return <Item module={entry} index={0} />;
          }}
        </DragOverlay>
      </DragDropProvider>

      <ShowDesktopButton />
    </div>
  );
}

// src/ui/svelte/fancy-toolbar/components/Toolbar.svelte
<script lang="ts">
  import { invoke, SeelenCommand, Widget } from "@seelen-ui/lib";
  import type { ContextMenu, ContextMenuItem, PluginId, WidgetId } from "@seelen-ui/lib/types";
  import { Alignment, FancyToolbarSide } from "@seelen-ui/lib/types";
  import { DragDropProvider, DragOverlay } from "@dnd-kit/svelte";
  import { move } from "@dnd-kit/helpers";
  import { onDestroy, onMount } from "svelte";
  import { BackgroundByLayers } from "libs/ui/svelte/components/BackgroundByLayers";
  import { getResourceText } from "libs/ui/react/utils/index.ts";
  import { DND_PLUGINS, DND_SENSORS } from "libs/ui/dnd.ts";
  import { t, locale } from "../i18n/index.ts";
  import {
    toolbarState,
    toolbarActions,
    plugins,
    restoreStateToDefault,
    HARDCODED_SEPARATOR_LEFT,
    HARDCODED_SEPARATOR_RIGHT,
  } from "../state/items.svelte.ts";
  import { settingsState } from "../state/settings.svelte.ts";
  import { hiddenByAutohide } from "../state/hidden.svelte.ts";
  import { windowsState } from "../state/windows.svelte.ts";
  import { matchIds } from "../utils.ts";
  import ItemsGroup from "./ItemsGroup.svelte";
  import CornerAction from "./CornerAction.svelte";
  import Item from "./Item.svelte";

  // ── Derived splits ───────────────────────────────────────────────────────

  const splittedItems = $derived.by(() => {
    const items = toolbarState.items;
    const idx1 = items.findIndex(
      (i) => typeof i !== "string" && i.id === HARDCODED_SEPARATOR_LEFT.id,
    );
    const idx2 = items.findIndex(
      (i) => typeof i !== "string" && i.id === HARDCODED_SEPARATOR_RIGHT.id,
    );
    return {
      left: items.slice(0, idx1),
      center: items.slice(idx1, idx2 + 1),
      right: items.slice(idx2 + 1),
    };
  });

  // ── Context menu ─────────────────────────────────────────────────────────

  const identifier = crypto.randomUUID();
  const modulesIdentifier = crypto.randomUUID();
  const onContextMenuClickEvent = "onContextMenuClick";
  const onTogglePluginEvent = "onTogglePlugin";

  let unlistenContextMenuClick: (() => void) | undefined;
  let unlistenTogglePlugin: (() => void) | undefined;

  onMount(() => {
    Widget.self.webview
      .listen(onContextMenuClickEvent, ({ payload }) => {
        const { key } = payload as any;
        if (key === "reoder") {
          toolbarState.state = {
            ...toolbarState.state,
            isReorderDisabled: !toolbarState.isReorderDisabled,
          };
        }
        if (key === "task_manager") {
          invoke(SeelenCommand.OpenFile, { path: "Taskmgr.exe" });
        }
        if (key === "settings") {
          invoke(SeelenCommand.TriggerWidget, {
            payload: { id: "@seelen/settings" as WidgetId },
          });
        }
        if (key === "restore") {
          restoreStateToDefault();
        }
      })
      .then((fn) => {
        unlistenContextMenuClick = fn;
      });

    Widget.self.webview
      .listen(onTogglePluginEvent, ({ payload }) => {
        const { key: pluginId, checked } = payload as any;
        if (checked) {
          toolbarActions.addItem(pluginId);
        } else {
          toolbarActions.removeItem(pluginId);
        }
      })
      .then((fn) => {
        unlistenTogglePlugin = fn;
      });
  });

  onDestroy(() => {
    unlistenContextMenuClick?.();
    unlistenTogglePlugin?.();
  });

  function buildContextMenu(): ContextMenu {
    const language = locale.value;

    function isAlreadyAdded(id: PluginId): boolean {
      return toolbarState.items.some((item) => item === id);
    }

    return {
      identifier,
      items: [
        {
          type: "Submenu",
          icon: "CgExtensionAdd",
          label: $t("context_menu.modules"),
          identifier: modulesIdentifier,
          items: [
            {
              type: "Item",
              key: "restore",
              icon: "TbRestore",
              label: $t("context_menu.restore"),
              callbackEvent: onContextMenuClickEvent,
            },
            { type: "Separator" },
            ...plugins.value
              .map<Extract<ContextMenuItem, { type: "Item" }>>((plugin) => ({
                type: "Item",
                key: plugin.id,
                label: getResourceText(plugin.metadata.displayName, language),
                icon: plugin.icon,
                callbackEvent: onTogglePluginEvent,
                checked: isAlreadyAdded(plugin.id),
              }))
              .toSorted((p1, p2) => p1.label.localeCompare(p2.label)),
          ],
        },
        { type: "Separator" },
        {
          type: "Item",
          key: "reoder",
          icon: toolbarState.isReorderDisabled ? "VscUnlock" : "VscLock",
          label: $t(
            toolbarState.isReorderDisabled
              ? "context_menu.reorder_enable"
              : "context_menu.reorder_disable",
          ),
          callbackEvent: onContextMenuClickEvent,
        },
        {
          type: "Item",
          key: "task_manager",
          icon: "PiChartLineFill",
          label: $t("context_menu.task_manager"),
          callbackEvent: onContextMenuClickEvent,
          checked: null,
          disabled: false,
        },
        {
          type: "Item",
          key: "settings",
          icon: "RiSettings4Fill",
          label: $t("context_menu.settings"),
          callbackEvent: onContextMenuClickEvent,
        },
      ],
    };
  }

  function handleContextMenu() {
    const alignY =
      settingsState.position === FancyToolbarSide.Bottom ? Alignment.End : Alignment.Start;
    invoke(SeelenCommand.TriggerContextMenu, {
      menu: { ...buildContextMenu(), alignX: Alignment.Center, alignY },
      forwardTo: null,
    });
  }

  // ── DnD ──────────────────────────────────────────────────────────────────

  function handleDragOver(event: any) {
    const temp = toolbarState.items.map((item) => (typeof item === "string" ? item : item.id));
    const newIds = move(temp, event);
    toolbarState.items = newIds.map((id) => toolbarState.items.find((i) => matchIds(i, id))!);
  }

  // ── Resolve overlay item ──────────────────────────────────────────────────

  function resolveOverlayModule(sourceId: string) {
    const entry = toolbarState.items.find((i) => matchIds(i, sourceId));
    if (!entry) return null;
    if (typeof entry === "string") {
      const plugin = plugins.value.find((p) => p.id === entry);
      if (!plugin) return null;
      return { ...(plugin.plugin as any), id: entry };
    }
    return entry;
  }
</script>

<div
  role="toolbar"
  tabindex="0"
  class="ft-bar {settingsState.position.toLowerCase()}"
  class:ft-bar-hidden={hiddenByAutohide.value}
  data-has-margin={!!settingsState.margin}
  data-there-is-maximized-on-background={windowsState.thereIsMaximizedOnBg}
  oncontextmenu={handleContextMenu}
>
  <CornerAction />
  <BackgroundByLayers />

  <DragDropProvider plugins={DND_PLUGINS} sensors={DND_SENSORS} onDragOver={handleDragOver}>
    <ItemsGroup id="left" items={splittedItems.left} startIndex={0} />
    <ItemsGroup id="center" items={splittedItems.center} startIndex={splittedItems.left.length} />
    <ItemsGroup
      id="right"
      items={splittedItems.right}
      startIndex={splittedItems.left.length + splittedItems.center.length}
    />

    <DragOverlay>
      {#snippet children(source)}
        {@const module = resolveOverlayModule(source.id as string)}
        {#if module}
          <Item {module} />
        {/if}
      {/snippet}
    </DragOverlay>
  </DragDropProvider>

  <CornerAction />
</div>
