// src/ui/svelte/media-popup/components/MediaDevice.svelte
<script lang="ts">
  import type { MediaDevice } from "@seelen-ui/lib/types";
  import { invoke, SeelenCommand } from "@seelen-ui/lib";
  import Icon from "libs/ui/svelte/components/Icon/Icon.svelte";
  import { t } from "../i18n";

  interface Props {
    device: MediaDevice;
    setViewDeviceId: (id: string) => void;
  }

  let { device, setViewDeviceId }: Props = $props();

  async function onClickMultimedia() {
    if (!device.isDefaultMultimedia) {
      try {
        await invoke(SeelenCommand.MediaSetDefaultDevice, {
          id: device.id,
          role: "multimedia",
        });
        await invoke(SeelenCommand.MediaSetDefaultDevice, {
          id: device.id,
          role: "console",
        });
      } catch (e) {
        console.error(e);
      }
    }
  }

  async function onClickCommunications() {
    if (!device.isDefaultCommunications) {
      try {
        await invoke(SeelenCommand.MediaSetDefaultDevice, {
          id: device.id,
          role: "communications",
        });
      } catch (e) {
        console.error(e);
      }
    }
  }
</script>

<div class="media-device">
  <div data-behavior="group">
    <button
      data-skin={device.isDefaultMultimedia ? "solid" : "default"}
      onclick={onClickMultimedia}
      title={$t("device.multimedia")}
    >
      <Icon iconName="IoMusicalNotes" size={14} />
    </button>
    <button
      data-skin={device.isDefaultCommunications ? "solid" : "default"}
      onclick={onClickCommunications}
      title={$t("device.comunications")}
    >
      <Icon iconName="FaPhoneFlip" size={12} />
    </button>
  </div>
  <span class="media-device-name">{device.name}</span>
  <button data-skin="transparent" onclick={() => setViewDeviceId(device.id)}>
    <Icon iconName="RiEqualizerLine" />
  </button>
</div>

// src/ui/toolbar/modules/media/infra/MediaDevice.tsx
import { SeelenCommand } from "@seelen-ui/lib";
import { MediaDevice } from "@seelen-ui/lib/types";
import { Icon } from "@shared/components/Icon";
import { OverflowTooltip } from "@shared/components/OverflowTooltip";
import { invoke } from "@tauri-apps/api/core";
import { Button, Tooltip } from "antd";
import { useTranslation } from "react-i18next";

export function Device({
  device,
  setViewDeviceId,
}: {
  device: MediaDevice;
  setViewDeviceId: (id: string) => void;
}) {
  const { t } = useTranslation();

  const onClickMultimedia = () => {
    if (!device.isDefaultMultimedia) {
      invoke(SeelenCommand.MediaSetDefaultDevice, {
        id: device.id,
        role: "multimedia",
      })
        .then(() =>
          invoke(SeelenCommand.MediaSetDefaultDevice, {
            id: device.id,
            role: "console",
          })
        )
        .catch(console.error);
    }
  };

  const onClickCommunications = () => {
    if (!device.isDefaultCommunications) {
      invoke(SeelenCommand.MediaSetDefaultDevice, {
        id: device.id,
        role: "communications",
      }).catch(
        console.error,
      );
    }
  };

  return (
    <div className="media-device">
      <Button.Group size="small">
        <Tooltip title={t("media.device.multimedia")}>
          <Button
            type={device.isDefaultMultimedia ? "primary" : "default"}
            onClick={onClickMultimedia}
          >
            <Icon iconName="IoMusicalNotes" size={14} />
          </Button>
        </Tooltip>
        <Tooltip title={t("media.device.comunications")}>
          <Button
            type={device.isDefaultCommunications ? "primary" : "default"}
            onClick={onClickCommunications}
          >
            <Icon iconName="FaPhoneFlip" size={12} />
          </Button>
        </Tooltip>
      </Button.Group>
      <OverflowTooltip text={device.name} />
      <button
        className="media-device-action"
        onClick={() => setViewDeviceId(device.id)}
      >
        <Icon iconName="RiEqualizerLine" />
      </button>
    </div>
  );
}

export function DeviceGroup({
  devices,
  setViewDeviceId,
}: {
  devices: MediaDevice[];
  setViewDeviceId: (id: string) => void;
}) {
  return (
    <div className="media-device-group">
      {devices.map((d) => <Device key={d.id} device={d} setViewDeviceId={setViewDeviceId} />)}
    </div>
  );
}
