// src/apps/seelen_wm/modules/layout/infra/containers/leaf.tsx
import { toPhysicalPixels } from '../../../../../utils';
import { cx } from '../../../../../utils/styles';
import { ReservedContainer } from './reserved';
import { invoke } from '@tauri-apps/api/core';
import { useCallback, useEffect, useRef } from 'react';
import { useSelector } from 'react-redux';

import { Selectors } from '../../../shared/store/app';

interface Props {
  hwnd: number;
  growFactor?: number;
}

export function LeafContainer({ hwnd, growFactor }: Props) {
  const ref = useRef<HTMLDivElement>(null);
  const reservation = useSelector(Selectors.reservation);
  const activeWindow = useSelector(Selectors.activeWindow);
  const borderSettings = useSelector(Selectors.settings.border);

  const updateSize = useCallback(() => {
    if (!ref.current) {
      return;
    }
    const domRect = ref.current.getBoundingClientRect();
    invoke('set_window_position', {
      hwnd: hwnd,
      rect: {
        top: toPhysicalPixels(domRect.top),
        left: toPhysicalPixels(domRect.left),
        right: toPhysicalPixels(domRect.width),
        bottom: toPhysicalPixels(domRect.height),
      },
    });
  }, [hwnd]);

  useEffect(updateSize);

  const isFocused = activeWindow === hwnd;
  return (
    <div
      ref={ref}
      style={{
        flexGrow: growFactor,
      }}
      className={cx('wm-container', 'wm-leaf', {
        'wm-leaf-focused': isFocused,
        'wm-leaf-with-borders': borderSettings.enabled,
      })}
    >
      {!!reservation && isFocused && <ReservedContainer reservation={reservation} />}
    </div>
  );
}

// src/ui/svelte/window_manager/modules/layout/infra/containers/Leaf.svelte
<script lang="ts">
  import { cx } from "@shared/styles";
  import { state } from "../../../shared/state.svelte.ts";
  // import { ReservedContainer } from './reserved';

  interface Props {
    hwnd: number;
    growFactor?: number;
  }

  let { hwnd, growFactor }: Props = $props();

  // Svelte 5 runes: $derived for computed values
  let isFocused = $derived(state.focusedApp.hwnd === hwnd);
</script>

<div
  data-hwnd={hwnd}
  style:flex-grow={growFactor}
  class={cx("wm-container", "wm-leaf", {
    "wm-leaf-focused": isFocused,
    "wm-leaf-with-borders": state.settings.border.enabled,
  })}
>
  <!-- {#if reservation && isFocused}
    <ReservedContainer {reservation} />
  {/if} -->
</div>
