// src/ui/react/window_manager/modules/layout/infra/containers/reserved.tsx
import { cx } from "@shared/styles";

import { Reservation } from "../../domain.ts";

import { $settings } from "../../../shared/state/mod.ts";

export function ReservedContainer(
  { reservation }: { reservation: Reservation },
) {
  const { floating } = $settings.value;
  return (
    <div
      className={cx(
        "wm-container",
        "wm-reserved",
        `wm-reserved-${reservation.toLowerCase()}`,
      )}
      style={reservation === Reservation.Float
        ? {
          width: floating.width,
          height: floating.height,
        }
        : undefined}
    />
  );
}

// src/ui/svelte/window_manager/modules/layout/infra/containers/Reserved.svelte
<script lang="ts">
  import { cx } from "@shared/styles";
  import { Reservation } from "../../domain.ts";
  import { state } from "../../../shared/state.svelte.ts";

  interface Props {
    reservation: Reservation;
  }

  let { reservation }: Props = $props();

  // Svelte 5 runes: $derived for computed values
  let floating = $derived(state.settings.floating);
</script>

<div
  class={cx("wm-container", "wm-reserved", `wm-reserved-${reservation.toLowerCase()}`)}
  style:width={reservation === Reservation.Float ? floating.width : undefined}
  style:height={reservation === Reservation.Float ? floating.height : undefined}
></div>
