// src/apps/toolbar/modules/media/infra/VolumeControl.tsx
import { SeelenCommand } from '@seelen-ui/lib';
import { invoke } from '@tauri-apps/api/core';
import { Slider, Tooltip } from 'antd';
import { throttle } from 'lodash';
import { memo, useCallback, useEffect, useState } from 'react';

import { Icon } from 'src/apps/shared/components/Icon';

interface Props {
  value: number;
  deviceId: string;
  sessionId?: string;
}

export const VolumeSlider = memo(({ value, deviceId, sessionId }: Props) => {
  const [internalValue, setInternalValue] = useState(value);

  useEffect(() => {
    setInternalValue(value);
  }, [value]);

  const onExternalChange = useCallback(
    throttle((value: number) => {
      invoke(SeelenCommand.SetVolumeLevel, { deviceId, sessionId, level: value }).catch(console.error);
    }, 100),
    [deviceId, sessionId],
  );

  const onInternalChange = (value: number) => {
    setInternalValue(value);
    onExternalChange(value);
  };

  function onWheel(e: WheelEvent) {
    const isUp = e.deltaY < 0;
    const level = Math.max(0, Math.min(1, internalValue + (isUp ? 0.02 : -0.02)));
    onInternalChange(level);
  }

  return (
    <div onWheel={onWheel}>
      <Slider
        value={internalValue}
        onChange={onInternalChange}
        min={0}
        max={1}
        step={0.01}
        tooltip={{
          formatter: (value) => `${(100 * (value || 0)).toFixed(0)}%`,
        }}
      />
    </div>
  );
});

interface VolumeControlProps {
  value: number;
  icon: React.ReactNode;
  deviceId: string;
  sessionName?: string;
  sessionId?: string;
  onRightAction?: () => void;
  withPercentage?: boolean;
}

export const VolumeControl = memo((props: VolumeControlProps) => {
  const {
    value,
    icon,
    deviceId,
    sessionName,
    sessionId,
    onRightAction,
    withPercentage = false,
  } = props;

  return (
    <div className="media-control-volume">
      <Tooltip title={sessionName}>
        <button
          className="media-control-volume-action"
          onClick={() => invoke(SeelenCommand.MediaToggleMute, { deviceId, sessionId })}
        >
          {icon}
        </button>
      </Tooltip>
      <VolumeSlider value={value} deviceId={deviceId} sessionId={sessionId} />
      {withPercentage && <span style={{ lineHeight: '100%' }}>{(100 * value).toFixed(0)}%</span>}
      {!!onRightAction && (
        <button className="media-control-volume-action" onClick={onRightAction}>
          <Icon iconName="RiEqualizerLine" />
        </button>
      )}
    </div>
  );
});

// src/ui/svelte/media-popup/components/VolumeControl.svelte
<script lang="ts">
  import { invoke, SeelenCommand } from "@seelen-ui/lib";
  import Icon from "libs/ui/svelte/components/Icon/Icon.svelte";
  import { throttle } from "lodash";

  interface Props {
    value: number;
    icon: string;
    deviceId: string;
    sessionName?: string;
    sessionId?: string;
    onRightAction?: () => void;
    withPercentage?: boolean;
    mutedIcon?: string;
    muted?: boolean;
  }

  let {
    value,
    icon,
    deviceId,
    sessionName,
    sessionId,
    onRightAction,
    withPercentage = false,
    mutedIcon,
    muted = false,
  }: Props = $props();

  let internalValue = $state(0);

  $effect(() => {
    internalValue = value;
  });

  const onExternalChange = throttle((value: number) => {
    invoke(SeelenCommand.SetVolumeLevel, {
      deviceId,
      sessionId: sessionId || null,
      level: value,
    }).catch(console.error);
  }, 100);

  function onInternalChange(value: number) {
    internalValue = value;
    onExternalChange(value);
  }

  function handleSliderChange(e: Event) {
    const target = e.target as HTMLInputElement;
    onInternalChange(Number(target.value));
  }

  function handleWheel(e: WheelEvent) {
    e.preventDefault();
    const isUp = e.deltaY < 0;
    const level = Math.max(0, Math.min(1, internalValue + (isUp ? 0.02 : -0.02)));
    onInternalChange(level);
  }

  async function toggleMute() {
    await invoke(SeelenCommand.MediaToggleMute, {
      deviceId,
      sessionId: sessionId || null,
    });
  }
</script>

<div class="media-control-volume">
  <button data-skin="transparent" onclick={toggleMute} title={sessionName}>
    <Icon iconName={(muted && mutedIcon ? mutedIcon : icon) as any} />
  </button>

  <input
    type="range"
    data-skin="flat"
    value={internalValue}
    min={0}
    max={1}
    step={0.01}
    onchange={handleSliderChange}
  />

  {#if onRightAction}
    <button data-skin="transparent" onclick={onRightAction}>
      <Icon iconName="RiEqualizerLine" />
    </button>
  {/if}
</div>
