// src/ui/svelte/user-menu/components/FilePreview.svelte
<script lang="ts">
  import type { File } from "@seelen-ui/lib/types";
  import { invoke, SeelenCommand } from "@seelen-ui/lib";
  import FileIcon from "libs/ui/svelte/components/Icon/FileIcon.svelte";
  import { WindowsDateFileTimeToDate, relativeTimeFromNow } from "libs/ui/svelte/utils";

  interface Props {
    file: File;
  }

  let { file }: Props = $props();

  const fileName = $derived(file.path.substring(file.path.lastIndexOf("\\") + 1));
  const lastAccessTime = $derived(relativeTimeFromNow(WindowsDateFileTimeToDate(file.lastAccessTime)));

  function selectFileOnExplorer() {
    invoke(SeelenCommand.SelectFileOnExplorer, { path: file.path });
  }
</script>

<button
  class="user-file"
  onclick={selectFileOnExplorer}
  title={file.path}
>
  <FileIcon class="user-file-icon" path={file.path} />
  <div class="user-file-label">{fileName}</div>
  <div class="user-file-date">{lastAccessTime}</div>
</button>

// src/apps/toolbar/modules/user/infra/FilePreview.tsx
import { invoke, SeelenCommand } from '@seelen-ui/lib';
import { File } from '@seelen-ui/lib/types';
import { Tooltip } from 'antd';
import moment from 'moment';

import { FileIcon } from 'src/apps/shared/components/Icon';

interface FilePreviewProps {
  file: File;
}

const EPOCH_DIFF_MILLISECONDS = 11644473600000n;

function WindowsDateFileTimeToDate(fileTime: bigint) {
  return new Date(Number(BigInt(fileTime) / 10000n - EPOCH_DIFF_MILLISECONDS));
}

export function FilePreview({ file }: FilePreviewProps) {
  return (
    <Tooltip mouseLeaveDelay={0} arrow={false} title={file.path} placement="right">
      <li
        className="userhome-file"
        onClick={() => invoke(SeelenCommand.SelectFileOnExplorer, { path: file.path })}
      >
        <FileIcon className="userhome-file-icon" path={file.path} />
        <div className="userhome-file-label">
          {file.path.substring(file.path.lastIndexOf('\\') + 1)}
        </div>
        <div className="userhome-file-date">
          {moment(WindowsDateFileTimeToDate(file.lastAccessTime)).fromNow()}
        </div>
      </li>
    </Tooltip>
  );
}
