// src/ui/svelte/weg/components/items/Separator.svelte
<script lang="ts">
  import { HARDCODED_SEPARATOR_LEFT, HARDCODED_SEPARATOR_RIGHT } from "../../state/items.svelte.ts";
  import { settingsState } from "../../state/settings.svelte.ts";
  import type { SeparatorWegItem } from "../../types.ts";

  interface Props {
    item: SeparatorWegItem;
  }

  let { item }: Props = $props();

  const isSeparator1 = $derived(item.id === HARDCODED_SEPARATOR_LEFT.id);
  const isSeparator2 = $derived(item.id === HARDCODED_SEPARATOR_RIGHT.id);
  const visible = $derived(settingsState.value?.visibleSeparators);
</script>

<div
  class="weg-separator"
  class:weg-separator-1={isSeparator1}
  class:weg-separator-2={isSeparator2}
  class:visible
></div>

// src/ui/react/weg/modules/item/infra/Separator.tsx
import { cx } from "libs/ui/react/utils/styling.ts";

import type { SeparatorWegItem } from "../../shared/types.ts";

import { HARDCODED_SEPARATOR_LEFT, HARDCODED_SEPARATOR_RIGHT } from "../../shared/state/items.ts";
import { $settings } from "../../shared/state/settings.ts";

export function Separator({ item }: { item: SeparatorWegItem }) {
  return (
    <div
      className={cx("weg-separator", {
        "weg-separator-1": item.id === HARDCODED_SEPARATOR_LEFT.id,
        "weg-separator-2": item.id === HARDCODED_SEPARATOR_RIGHT.id,
        visible: $settings.value.visibleSeparators,
      })}
    />
  );
}
