// src/ui/svelte/weg/components/items/ShowDesktop.svelte
<script lang="ts">
  import { invoke, SeelenCommand } from "@seelen-ui/lib";
  import { SpecificIcon } from "libs/ui/svelte/components/Icon/index.ts";
  import { t } from "../../i18n/index.ts";
  import type { ShowDesktopWegItem } from "../../types.ts";
  import { settingsState, getDockContextMenuAlignment } from "../../state/settings.svelte.ts";
  import { getMenuForItem } from "../../generalMenu.ts";

  interface Props {
    item: ShowDesktopWegItem;
  }

  let { item }: Props = $props();

  function onClick() {
    invoke(SeelenCommand.ShowDesktop);
  }

  function onContextMenu(e: MouseEvent) {
    e.stopPropagation();
    const { alignX, alignY } = getDockContextMenuAlignment(settingsState.position);
    invoke(SeelenCommand.TriggerContextMenu, {
      menu: { ...getMenuForItem($t, item), alignX, alignY },
      forwardTo: null,
    });
  }
</script>

<div
  role="button"
  tabindex="0"
  class="weg-item weg-item-show-desktop"
  onclick={onClick}
  oncontextmenu={onContextMenu}
  onkeypress={() => {}}
>
  <SpecificIcon class="weg-item-icon" name="@seelen/weg::show-desktop" />
</div>

// src/ui/react/weg/modules/item/infra/ShowDesktop.tsx
import { invoke, SeelenCommand } from "@seelen-ui/lib";
import { SpecificIcon } from "libs/ui/react/components/Icon/index.tsx";
import { memo, useCallback } from "react";
import { useTranslation } from "react-i18next";

import type { ShowDesktopWegItem } from "../../shared/types.ts";

import { $settings, getDockContextMenuAlignment } from "../../shared/state/settings.ts";
import { getMenuForItem } from "./GeneralMenu.tsx";

interface Props {
  item: ShowDesktopWegItem;
}

export const ShowDesktopModule = memo(({ item }: Props) => {
  const { t } = useTranslation();

  const onContextMenu = useCallback(
    (e: MouseEvent) => {
      e.stopPropagation();
      const { alignX, alignY } = getDockContextMenuAlignment($settings.value.position);
      invoke(SeelenCommand.TriggerContextMenu, {
        menu: { ...getMenuForItem(t, item), alignX, alignY },
        forwardTo: null,
      });
    },
    [item, t],
  );

  return (
    <div
      className="weg-item weg-item-show-desktop"
      onClick={() => {
        invoke(SeelenCommand.ShowDesktop);
      }}
      onContextMenu={onContextMenu}
    >
      <SpecificIcon className="weg-item-icon" name="@seelen/weg::show-desktop" />
    </div>
  );
});
