// src/ui/weg/modules/item/infra/StartMenu.tsx
import { SeelenCommand } from '@seelen-ui/lib';
import { SpecificIcon } from '@shared/components/Icon';
import { invoke } from '@tauri-apps/api/core';
import { memo } from 'react';
import { useTranslation } from 'react-i18next';
import { useSelector } from 'react-redux';

import { BackgroundByLayersV2 } from '@shared/components/BackgroundByLayers/infra';

import { Selectors } from '../../shared/store/app';

import { StartMenuWegItem } from '../../shared/store/domain';

import { WithContextMenu } from '../../../components/WithContextMenu';
import { getMenuForItem } from './Menu';

interface Props {
  item: StartMenuWegItem;
}

const startMenuExes = ['SearchHost.exe', 'StartMenuExperienceHost.exe'];

export const StartMenu = memo(({ item }: Props) => {
  const focused = useSelector(Selectors.focusedApp);

  const { t } = useTranslation();

  const isStartMenuOpen = startMenuExes.some((program) => (focused?.exe || '').endsWith(program));

  return (
    <WithContextMenu items={getMenuForItem(t, item)}>
      <div
        className="weg-item weg-item-start"
        onClick={() => {
          if (!isStartMenuOpen) {
            invoke(SeelenCommand.SendKeys, { keys: '{win}' });
          }
        }}
        onContextMenu={(e) => e.stopPropagation()}
      >
        <BackgroundByLayersV2 />
        <SpecificIcon
          className="weg-item-icon weg-item-start-icon"
          name={'@seelen/weg::start-menu'}
        />
      </div>
    </WithContextMenu>
  );
});

// src/ui/svelte/weg/components/items/StartMenu.svelte
<script lang="ts">
  import { invoke, SeelenCommand } from "@seelen-ui/lib";
  import { SpecificIcon } from "libs/ui/svelte/components/Icon/index.ts";
  import { t } from "../../i18n/index.ts";
  import type { StartMenuWegItem } from "../../types.ts";
  import { settingsState } from "../../state/settings.svelte.ts";
  import { getMenuForItem } from "../../generalMenu.ts";
  import { windowsState } from "../../state/windows.svelte.ts";

  interface Props {
    item: StartMenuWegItem;
  }

  let { item }: Props = $props();

  const startMenuExes = ["SearchHost.exe", "StartMenuExperienceHost.exe"];
  const isStartMenuOpen = $derived(
    startMenuExes.some((program) => (windowsState.delayedFocused?.exe || "").endsWith(program)),
  );

  function onClick() {
    if (!isStartMenuOpen) {
      invoke(SeelenCommand.ShowStartMenu);
    }
  }

  function onContextMenu(e: MouseEvent) {
    e.stopPropagation();
    const alignX = settingsState.popupAlignX;
    const alignY = settingsState.popupAlignY;
    invoke(SeelenCommand.TriggerContextMenu, {
      menu: { ...getMenuForItem($t, item), alignX, alignY },
      forwardTo: null,
    });
  }
</script>

<div
  role="button"
  tabindex="0"
  class="weg-item weg-item-start"
  onclick={onClick}
  oncontextmenu={onContextMenu}
  onkeypress={() => {}}
>
  <SpecificIcon class="weg-item-icon weg-item-start-icon" name="@seelen/weg::start-menu" />
</div>
