// src/ui/seelenweg/modules/item/infra/UserApplicationPreview.tsx
import { SeelenCommand } from '@seelen-ui/lib';
import { convertFileSrc, invoke } from '@tauri-apps/api/core';
import { listen } from '@tauri-apps/api/event';
import { tempDir } from '@tauri-apps/api/path';
import { Spin } from 'antd';
import React, { useEffect, useReducer, useState } from 'react';

import { HWND } from '../../shared/store/domain';

import { Icon } from '../../../../shared/components/Icon';
import { cx } from '../../../../shared/styles';
import { $settings } from '../../shared/state/mod';
interface PreviewProps {
  title: string;
  hwnd: HWND;
  isFocused: boolean;
}

const TEMP_FOLDER = await tempDir();

export const UserApplicationPreview = ({ title, hwnd, isFocused }: PreviewProps) => {
  const imageUrl = convertFileSrc(`${TEMP_FOLDER}${hwnd}.png`);

  const [imageSrc, setImageSrc] = useState<string | null>(imageUrl);
  const [_, forceUpdate] = useReducer((x) => x + 1, 0);

  useEffect(() => {
    const unlisten = listen(`weg-preview-update-${hwnd}`, () => {
      setImageSrc(imageUrl);
      forceUpdate(_);
    });
    return () => {
      unlisten.then((unlisten) => unlisten()).catch(console.error);
    };
  }, []);

  const onClose = (e: React.MouseEvent<HTMLDivElement>) => {
    e.stopPropagation();
    invoke(SeelenCommand.WegCloseApp, { hwnd });
  };

  return (
    <div
      className={cx('weg-item-preview', {
        'weg-item-preview-thumbnail-disabled': !$settings.value.thumbnailGenerationEnabled,
      })}
      onClick={() => {
        invoke(SeelenCommand.WegToggleWindowState, { hwnd, wasFocused: isFocused });
      }}
    >
      <div className="weg-item-preview-topbar">
        <div className="weg-item-preview-title">{title}</div>
        <div className="weg-item-preview-close" onClick={onClose}>
          <Icon iconName="IoClose" />
        </div>
      </div>
      {$settings.value.thumbnailGenerationEnabled && (
        <div className="weg-item-preview-image-container">
          {imageSrc ? (
            <img
              className="weg-item-preview-image"
              src={imageSrc + `?${new Date().getTime()}`}
              onError={() => setImageSrc(null)}
            />
          ) : (
            <Spin className="weg-item-preview-spin" />
          )}
        </div>
      )}
    </div>
  );
};

// src/ui/svelte/weg/components/items/UserApplicationPreview.svelte
<script lang="ts">
  import { invoke, SeelenCommand } from "@seelen-ui/lib";
  import { Icon, MissingIcon } from "libs/ui/svelte/components/Icon/index.ts";
  import { delayedFocused, previews } from "../../state/windows.svelte.ts";

  interface Props {
    title: string;
    hwnd: number;
  }

  let { title, hwnd }: Props = $props();

  const preview = $derived(previews.value[hwnd]);

  function onClick() {
    invoke(SeelenCommand.WegToggleWindowState, {
      hwnd,
      wasFocused: delayedFocused.value?.hwnd === hwnd,
    });
  }

  function onAuxClick(e: MouseEvent) {
    if (e.button === 1) {
      invoke(SeelenCommand.WegCloseApp, { hwnd });
    }
  }

  function onClose(e: MouseEvent) {
    e.stopPropagation();
    invoke(SeelenCommand.WegCloseApp, { hwnd });
  }
</script>

<div
  role="button"
  tabindex="0"
  class="weg-item-preview"
  onclick={onClick}
  onauxclick={onAuxClick}
  onkeypress={() => {}}
>
  <div class="weg-item-preview-topbar">
    <div class="weg-item-preview-title">{title}</div>
    <button data-skin="transparent" onclick={onClose}>
      <Icon iconName="IoClose" />
    </button>
  </div>
  <div class="weg-item-preview-image-container">
    {#if preview}
      <img class="weg-item-preview-image" src="data:image/webp;base64,{preview.data}" alt={title} />
    {:else}
      <MissingIcon class="weg-item-no-preview" />
    {/if}
  </div>
</div>
