// src/ui/react/weg/modules/item/infra/UserApplicationPreview.tsx
import { SeelenCommand } from "@seelen-ui/lib";
import { Icon, MissingIcon } from "libs/ui/react/components/Icon/index.tsx";
import { invoke } from "@tauri-apps/api/core";

import { $delayedFocused, $previews } from "../../shared/state/windows.ts";
import type { TargetedMouseEvent } from "preact";

interface PreviewProps {
  title: string;
  hwnd: number;
}

export const UserApplicationPreview = ({ title, hwnd }: PreviewProps) => {
  const preview = $previews.value[hwnd];

  function onClick() {
    invoke(SeelenCommand.WegToggleWindowState, {
      hwnd,
      wasFocused: $delayedFocused.value?.hwnd === hwnd,
    });
  }

  function onAuxClick(e: TargetedMouseEvent<HTMLDivElement>) {
    if (e.button === 1) {
      invoke(SeelenCommand.WegCloseApp, { hwnd });
    }
  }

  function onClose(e: TargetedMouseEvent<HTMLButtonElement>) {
    e.stopPropagation();
    invoke(SeelenCommand.WegCloseApp, { hwnd });
  }

  return (
    <div className="weg-item-preview" onClick={onClick} onAuxClick={onAuxClick}>
      <div className="weg-item-preview-topbar">
        <div className="weg-item-preview-title">{title}</div>
        <button data-skin="transparent" onClick={onClose}>
          <Icon iconName="IoClose" />
        </button>
      </div>
      <div className="weg-item-preview-image-container">
        {preview
          ? (
            <img
              className="weg-item-preview-image"
              src={`data:image/webp;base64,${preview.data}`}
            />
          )
          : <MissingIcon className="weg-item-no-preview" />}
      </div>
    </div>
  );
};

// src/ui/svelte/weg/components/items/UserApplicationPreview.svelte
<script lang="ts">
  import { invoke, SeelenCommand } from "@seelen-ui/lib";
  import { Icon, MissingIcon } from "libs/ui/svelte/components/Icon/index.ts";
  import { delayedFocused, previews } from "../../state/windows.svelte.ts";

  interface Props {
    title: string;
    hwnd: number;
  }

  let { title, hwnd }: Props = $props();

  const preview = $derived(previews.value[hwnd]);

  function onClick() {
    invoke(SeelenCommand.WegToggleWindowState, {
      hwnd,
      wasFocused: delayedFocused.value?.hwnd === hwnd,
    });
  }

  function onAuxClick(e: MouseEvent) {
    if (e.button === 1) {
      invoke(SeelenCommand.WegCloseApp, { hwnd });
    }
  }

  function onClose(e: MouseEvent) {
    e.stopPropagation();
    invoke(SeelenCommand.WegCloseApp, { hwnd });
  }
</script>

<div
  role="button"
  tabindex="0"
  class="weg-item-preview"
  onclick={onClick}
  onauxclick={onAuxClick}
  onkeypress={() => {}}
>
  <div class="weg-item-preview-topbar">
    <div class="weg-item-preview-title">{title}</div>
    <button data-skin="transparent" onclick={onClose}>
      <Icon iconName="IoClose" />
    </button>
  </div>
  <div class="weg-item-preview-image-container">
    {#if preview}
      <img class="weg-item-preview-image" src="data:image/webp;base64,{preview.data}" alt={title} />
    {:else}
      <MissingIcon class="weg-item-no-preview" />
    {/if}
  </div>
</div>
