// src/ui/react/toolbar/modules/user/infra/UserProfile.tsx
import { invoke, SeelenCommand } from "@seelen-ui/lib";
import type { User } from "@seelen-ui/lib/types";
import { Icon, MissingIcon } from "libs/ui/react/components/Icon";
import { path } from "@tauri-apps/api";
import { convertFileSrc } from "@tauri-apps/api/core";
import { Tooltip } from "antd";
import { useTranslation } from "react-i18next";

interface Props {
  user: User;
}

export function UserProfile({ user }: Props) {
  const { t } = useTranslation();

  return (
    <div className="userhome-profile-container">
      <div className="userhome-profile-picture-container">
        {user.profilePicturePath
          ? (
            <img
              className="userhome-profile-picture"
              src={convertFileSrc(user.profilePicturePath)}
            />
          )
          : <MissingIcon />}
        <Tooltip
          mouseLeaveDelay={0}
          arrow={false}
          title={t("settings.log_out")}
          placement="bottom"
        >
          <button
            className="userhome-profile-lock-button"
            onClick={() => invoke(SeelenCommand.LogOut)}
          >
            <Icon iconName="BiLogOut" />
          </button>
        </Tooltip>
        <Tooltip
          mouseLeaveDelay={0}
          arrow={false}
          title={t("userhome.profile.accounts")}
          placement="bottom"
        >
          <button
            className="userhome-profile-settings-button"
            onClick={() => invoke(SeelenCommand.OpenFile, { path: "ms-settings:accounts" })}
          >
            <Icon iconName="RiSettings3Fill" />
          </button>
        </Tooltip>
      </div>

      <div className="userhome-profile-information">
        <div className="userhome-profile-name">
          <span>{user.name}</span>
          <Tooltip
            mouseLeaveDelay={0}
            arrow={false}
            title={t("userhome.profile.open_user_folder")}
            placement="right"
          >
            <button
              className="userhome-profile-action-button"
              onClick={async () => {
                invoke(SeelenCommand.OpenFile, { path: await path.homeDir() });
              }}
            >
              <Icon iconName="PiFolderUser" />
            </button>
          </Tooltip>
        </div>

        <div className="userhome-profile-email">{user.email}</div>

        <Tooltip
          mouseLeaveDelay={0}
          arrow={false}
          title={t("userhome.profile.open_onedrive")}
          placement="right"
        >
          <button
            className="userhome-profile-action-button"
            onClick={() => {
              if (user.oneDrivePath) {
                invoke(SeelenCommand.OpenFile, { path: user.oneDrivePath });
              }
            }}
          >
            <Icon iconName="ImOnedrive" />
            <span>OneDrive</span>
          </button>
        </Tooltip>
      </div>
    </div>
  );
}

// src/ui/svelte/user-menu/components/UserProfile.svelte
<script lang="ts">
  import type { User } from "@seelen-ui/lib/types";
  import { invoke, SeelenCommand } from "@seelen-ui/lib";
  import { convertFileSrc } from "@tauri-apps/api/core";
  import { path } from "@tauri-apps/api";
  import Icon from "libs/ui/svelte/components/Icon/Icon.svelte";
  import { t } from "../i18n";

  interface Props {
    user: User;
  }

  let { user }: Props = $props();

  async function openUserFolder() {
    invoke(SeelenCommand.OpenFile, { path: await path.homeDir() });
  }

  function openOneDrive() {
    if (user.oneDrivePath) {
      invoke(SeelenCommand.OpenFile, { path: user.oneDrivePath });
    }
  }

  function openAccountSettings() {
    invoke(SeelenCommand.OpenFile, { path: "ms-settings:accounts" });
  }

  function logOut() {
    invoke(SeelenCommand.LogOut);
  }
</script>

<div class="user-profile-container">
  <div class="user-profile-picture-container">
    {#if user.profilePicturePath}
      <img
        class="user-profile-picture"
        src={convertFileSrc(user.profilePicturePath)}
        alt={user.name}
      />
    {:else}
      <div class="user-profile-picture-fallback">
        <Icon iconName="PiFolderUser" />
      </div>
    {/if}
    <button
      class="user-profile-lock-button"
      onclick={logOut}
      title={$t("profile.log_out")}
    >
      <Icon iconName="BiLogOut" />
    </button>
    <button
      class="user-profile-settings-button"
      onclick={openAccountSettings}
      title={$t("profile.accounts")}
    >
      <Icon iconName="RiSettings3Fill" />
    </button>
  </div>

  <div class="user-profile-information">
    <div class="user-profile-name">
      <span>{user.name}</span>
      <button
        class="user-profile-action-button"
        onclick={openUserFolder}
        title={$t("profile.open_user_folder")}
      >
        <Icon iconName="PiFolderUser" />
      </button>
    </div>

    {#if user.email}
      <div class="user-profile-email">{user.email}</div>
    {/if}

    {#if user.oneDrivePath}
      <button
        class="user-profile-action-button"
        onclick={openOneDrive}
        title={$t("profile.open_onedrive")}
      >
        <Icon iconName="ImOnedrive" />
        <span>OneDrive</span>
      </button>
    {/if}
  </div>
</div>
