// src/ui/svelte/media-popup/components/MediaPlayer.svelte
<script lang="ts">
  import type { MediaPlayer } from "@seelen-ui/lib/types";
  import { invoke, SeelenCommand } from "@seelen-ui/lib";
  import { Icon, FileIcon } from "libs/ui/svelte/components/Icon";
  import { path } from "@tauri-apps/api";
  import { convertFileSrc } from "@tauri-apps/api/core";

  interface Props {
    session: MediaPlayer;
  }

  let { session }: Props = $props();

  const MAX_LUMINANCE = 210;
  const MIN_LUMINANCE = 40;
  const BRIGHTNESS_MULTIPLIER = 1.5;

  let luminance = $state(0);
  let defaultThumbnail = $state("");

  async function initDefaultThumbnail() {
    defaultThumbnail = await path.resolve(
      await path.resourceDir(),
      "static",
      "icons",
      "music_thumbnail.jpg",
    );
  }

  initDefaultThumbnail();

  let thumbnailSrc = $derived(convertFileSrc(session?.thumbnail || defaultThumbnail));

  function calcLuminance(imageUrl: string): Promise<number> {
    return new Promise((resolve, reject) => {
      const img = new Image();
      img.crossOrigin = "Anonymous";
      img.src = imageUrl;

      img.onload = () => {
        const canvas = document.createElement("canvas");
        const ctx = canvas.getContext("2d");

        if (!ctx) {
          reject(new Error("Unable to get canvas context"));
          return;
        }

        canvas.width = img.width;
        canvas.height = img.height;
        ctx.drawImage(img, 0, 0, img.width, img.height);

        const imageData = ctx.getImageData(0, 0, img.width, img.height);
        const data = imageData.data;
        let totalLuminance = 0;

        for (let i = 0; i < data.length; i += 4) {
          const r = data[i] || 0;
          const g = data[i + 1] || 0;
          const b = data[i + 2] || 0;

          const lum = 0.299 * r + 0.587 * g + 0.114 * b;
          totalLuminance += lum;
        }

        const avgLuminance = totalLuminance / (data.length / 4);
        resolve(avgLuminance);
      };

      img.onerror = (err) => {
        reject(err);
      };
    });
  }

  $effect(() => {
    calcLuminance(thumbnailSrc)
      .then((lum) => (luminance = lum))
      .catch(console.error);
  });

  const filteredLuminance = $derived(
    Math.max(Math.min(luminance * BRIGHTNESS_MULTIPLIER, MAX_LUMINANCE), MIN_LUMINANCE),
  );

  const color = $derived(filteredLuminance < 125 ? "#efefef" : "#222222");

  function onClickBtn(cmd: SeelenCommand) {
    invoke(cmd, { id: session.umid }).catch(console.error);
  }
</script>

<div
  class="media-session"
  style:background-color="rgb({filteredLuminance}, {filteredLuminance}, {filteredLuminance})"
>
  <img class="media-session-blurred-thumbnail" src={thumbnailSrc} alt="" />
  <div class="media-session-thumbnail-container">
    <FileIcon class="media-session-app-icon" umid={session.umid} title={session.owner.name} />
    <img class="media-session-thumbnail" src={thumbnailSrc} alt="" />
  </div>

  <div class="media-session-info" style:color>
    <h4 class="media-session-title">{session.title}</h4>
    <span class="media-session-author">{session.author}</span>
    <div class="media-session-actions">
      <button data-skin="transparent" onclick={() => onClickBtn(SeelenCommand.MediaPrev)}>
        <Icon iconName="TbPlayerSkipBackFilled" {color} />
      </button>
      <button
        data-skin="transparent"
        onclick={() => onClickBtn(SeelenCommand.MediaTogglePlayPause)}
      >
        <Icon iconName={session.playing ? "TbPlayerPauseFilled" : "TbPlayerPlayFilled"} {color} />
      </button>
      <button data-skin="transparent" onclick={() => onClickBtn(SeelenCommand.MediaNext)}>
        <Icon iconName="TbPlayerSkipForwardFilled" {color} />
      </button>
    </div>
  </div>
</div>

// src/apps/toolbar/modules/media/infra/MediaPlayer.tsx
import { SeelenCommand } from '@seelen-ui/lib';
import { MediaPlayer } from '@seelen-ui/lib/types';
import { path } from '@tauri-apps/api';
import { convertFileSrc, invoke } from '@tauri-apps/api/core';
import { Button, Tooltip } from 'antd';
import { useEffect, useState } from 'react';

import { calcLuminance } from '../application';
import { FileIcon, Icon } from 'src/apps/shared/components/Icon';

const MAX_LUMINANCE = 210;
const MIN_LUMINANCE = 40;
const BRIGHTNESS_MULTIPLIER = 1.5; // used in css

const DEFAULT_THUMBNAIL = await path.resolve(
  await path.resourceDir(),
  'static',
  'icons',
  'music_thumbnail.jpg',
);

export function MediaPlayerSession({ session }: { session: MediaPlayer }) {
  const [luminance, setLuminance] = useState(0);

  let thumbnailSrc = convertFileSrc(session?.thumbnail ? session.thumbnail : DEFAULT_THUMBNAIL);

  useEffect(() => {
    calcLuminance(thumbnailSrc).then(setLuminance).catch(console.error);
  }, [thumbnailSrc]);

  const filteredLuminance = Math.max(
    Math.min(luminance * BRIGHTNESS_MULTIPLIER, MAX_LUMINANCE),
    MIN_LUMINANCE,
  );
  const color = filteredLuminance < 125 ? '#efefef' : '#222222';

  const onClickBtn = (cmd: string) => {
    invoke(cmd, { id: session.umid }).catch(console.error);
  };

  return (
    <div
      className="media-session"
      style={{
        backgroundColor: `rgb(${filteredLuminance}, ${filteredLuminance}, ${filteredLuminance})`,
      }}
    >
      <img className="media-session-blurred-thumbnail" src={thumbnailSrc} />
      <div className="media-session-thumbnail-container">
        <Tooltip title={session.owner.name} placement="bottom">
          <FileIcon className="media-session-app-icon" umid={session.umid} />
        </Tooltip>
        <img className="media-session-thumbnail" src={thumbnailSrc} />
      </div>

      <div className="media-session-info" style={{ color }}>
        <h4 className="media-session-title">{session.title}</h4>
        <span className="media-session-author">{session.author}</span>
        <div className="media-session-actions">
          <Button type="text" onClick={onClickBtn.bind(null, SeelenCommand.MediaPrev)}>
            <Icon iconName="TbPlayerSkipBackFilled" color={color} />
          </Button>
          <Button type="text" onClick={onClickBtn.bind(null, SeelenCommand.MediaTogglePlayPause)}>
            <Icon
              iconName={session.playing ? 'TbPlayerPauseFilled' : 'TbPlayerPlayFilled'}
              color={color}
            />
          </Button>
          <Button type="text" onClick={onClickBtn.bind(null, SeelenCommand.MediaNext)}>
            <Icon iconName="TbPlayerSkipForwardFilled" color={color} />
          </Button>
        </div>
      </div>
    </div>
  );
}
